### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Panos13L** [gzoumpourlis/DEAP_MNE_preprocessing#1]
Can we use this code for feature extraction if we have the data into 32 seperate .mat files( one .mat file for each subject) ?

**Comment by gzoumpourlis** [comment]
> Can we use this code for feature extraction if we have the data into 32 seperate .mat files( one .mat file for each subject) ?

Hi @Panos13L,

In the ``clean_DEAP.py`` file, the code saves a [3-dimensional numpy array](https://github.com/gzoumpourlis/DEAP_MNE_preprocessing/blob/main/clean_DEAP.py#L179) of size N_trials x N_channels x duration, containing the preprocessed EEG signals. Note that the pre-trial baseline period is also included in this array.

Then, in the ``extract_features_DEAP.py`` file, the code [loads the aforementioned numpy array](https://github.com/gzoumpourlis/DEAP_MNE_preprocessing/blob/main/extract_features_DEAP.py#L299), and proceeds with feature extraction.

So you can adapt the 2nd file to operate on .mat files instead of .npy files, under the assumption that you ensure everything is the same (channel order, baseline+trial epoching, etc).
